CREATE TABLE `immobili_fotovoltaico` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tipo` enum('capannone','terreno') NOT NULL,
	`titolo` varchar(255) NOT NULL,
	`regione` varchar(100),
	`provincia` varchar(5),
	`comune` varchar(100),
	`indirizzo` varchar(255),
	`superficieMq` int,
	`superficieEttari` decimal(8,2),
	`attivitaEnergivora` boolean DEFAULT false,
	`tipoAttivita` varchar(100),
	`vicinanzaAutostrada` boolean DEFAULT false,
	`vicinanzaAreaIndustriale` boolean DEFAULT false,
	`distanzaAutostradaKm` decimal(5,1),
	`distanzaAreaIndustrialeKm` decimal(5,1),
	`potenzaStimataKwp` decimal(8,2),
	`disponibilita` enum('vendita','affitto','disponibile','trattativa') NOT NULL DEFAULT 'disponibile',
	`prezzoEuro` decimal(12,2),
	`nomeContatto` varchar(255),
	`telefonoContatto` varchar(30),
	`emailContatto` varchar(255),
	`note` text,
	`pubblicato` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `immobili_fotovoltaico_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prospect_installatori` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ragioneSociale` varchar(255) NOT NULL,
	`settore` varchar(100),
	`regione` varchar(100),
	`provincia` varchar(5),
	`comune` varchar(100),
	`indirizzo` varchar(255),
	`telefono` varchar(30),
	`email` varchar(255),
	`sito` varchar(255),
	`fasciaFatturato` enum('sotto_100k','100k_500k','500k_1m','1m_5m','sopra_5m'),
	`dipendenti` int,
	`statoContatto` enum('da_contattare','contattato','interessato','cliente','non_interessato') NOT NULL DEFAULT 'da_contattare',
	`note` text,
	`fonte` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `prospect_installatori_id` PRIMARY KEY(`id`)
);
