// Listino Prezzi Soluzioni Ambientali - Rev. 13/03/2026
// 3 fasce: standard, forniture_fv (forniture fotovoltaiche), premium

export interface ServizioListino {
  id: string;
  categoria: string;
  nome: string;
  descrizione: string;
  prezzoStandard: number | string;
  prezzoForniture: number | string;
  prezzoPremium: number | string;
  notePrezzo?: string;
}

export const LISTINO: ServizioListino[] = [

  // ─── PROGETTAZIONE ───────────────────────────────────────────────────────────
  // Include: Inquadramento urbanistico, Layout Cartografico, Layout Stato di progetto,
  // Schema unifilare, Relazione tecnica impianto, Relazione generale,
  // Dichiarazioni per gestione rifiuti da cantiere, Procedura PAS/DILA
  {
    id: "prog-1",
    categoria: "Progettazione",
    nome: "Progetto Impianto FV fino a 10 kWp",
    descrizione: "Progettazione completa impianto fotovoltaico fino a 10 kWp. Include inquadramento urbanistico, layout cartografico, schema unifilare, relazione tecnica, procedura PAS/DILA.",
    prezzoStandard: 2500,
    prezzoForniture: 2500,
    prezzoPremium: 2500,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-2",
    categoria: "Progettazione",
    nome: "Progetto Impianto FV fino a 30 kWp",
    descrizione: "Progettazione completa impianto fotovoltaico fino a 30 kWp. Include inquadramento urbanistico, layout cartografico, schema unifilare, relazione tecnica, procedura PAS/DILA.",
    prezzoStandard: 4000,
    prezzoForniture: 4000,
    prezzoPremium: 4000,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-3",
    categoria: "Progettazione",
    nome: "Progetto Impianto FV fino a 60 kWp",
    descrizione: "Progettazione completa impianto fotovoltaico fino a 60 kWp. Include inquadramento urbanistico, layout cartografico, schema unifilare, relazione tecnica, procedura PAS/DILA.",
    prezzoStandard: 7500,
    prezzoForniture: 7500,
    prezzoPremium: 7500,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-4",
    categoria: "Progettazione",
    nome: "Progetto Impianto FV fino a 100 kWp",
    descrizione: "Progettazione completa impianto fotovoltaico fino a 100 kWp. Include inquadramento urbanistico, layout cartografico, schema unifilare, relazione tecnica, procedura PAS/DILA.",
    prezzoStandard: 12000,
    prezzoForniture: 12000,
    prezzoPremium: 12000,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-5",
    categoria: "Progettazione",
    nome: "Progetto Impianto FV fino a 500 kWp",
    descrizione: "Progettazione completa impianto fotovoltaico fino a 500 kWp. Include inquadramento urbanistico, layout cartografico, schema unifilare, relazione tecnica, procedura PAS/DILA.",
    prezzoStandard: 15000,
    prezzoForniture: 15000,
    prezzoPremium: 15000,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-6",
    categoria: "Progettazione",
    nome: "Progetto Impianto FV fino a 1 MW",
    descrizione: "Progettazione completa impianto fotovoltaico fino a 1 MW. Include inquadramento urbanistico, layout cartografico, schema unifilare, relazione tecnica, procedura PAS/DILA.",
    prezzoStandard: 20000,
    prezzoForniture: 20000,
    prezzoPremium: 20000,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-7",
    categoria: "Progettazione",
    nome: "Progetto Impianto FV fino a 2 MW",
    descrizione: "Progettazione completa impianto fotovoltaico fino a 2 MW. Include inquadramento urbanistico, layout cartografico, schema unifilare, relazione tecnica, procedura PAS/DILA.",
    prezzoStandard: 25000,
    prezzoForniture: 25000,
    prezzoPremium: 25000,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-8",
    categoria: "Progettazione",
    nome: "Direzione Lavori e Sicurezza fino a 500 kWp",
    descrizione: "Attività di Direzione Lavori e Sicurezza per impianti fotovoltaici fino a 500 kWp.",
    prezzoStandard: 7000,
    prezzoForniture: 7000,
    prezzoPremium: 7000,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-9",
    categoria: "Progettazione",
    nome: "Direzione Lavori e Sicurezza fino a 1 MW",
    descrizione: "Attività di Direzione Lavori e Sicurezza per impianti fotovoltaici fino a 1 MW.",
    prezzoStandard: 8000,
    prezzoForniture: 8000,
    prezzoPremium: 8000,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-10",
    categoria: "Progettazione",
    nome: "Relazione Tecnica Asseverata Agrisolare fino a 20 kWp",
    descrizione: "Elaborazione relazione tecnica asseverata per bando Agrisolare fino a 20 kWp.",
    prezzoStandard: 800,
    prezzoForniture: 800,
    prezzoPremium: 800,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-11",
    categoria: "Progettazione",
    nome: "Relazione Tecnica Asseverata Agrisolare fino a 50 kWp",
    descrizione: "Elaborazione relazione tecnica asseverata per bando Agrisolare fino a 50 kWp.",
    prezzoStandard: 1000,
    prezzoForniture: 1000,
    prezzoPremium: 1000,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "prog-12",
    categoria: "Progettazione",
    nome: "Relazione Tecnica Asseverata Agrisolare oltre 50 kWp",
    descrizione: "Elaborazione relazione tecnica asseverata per bando Agrisolare oltre 50 kWp.",
    prezzoStandard: "Da concordare",
    prezzoForniture: "Da concordare",
    prezzoPremium: "Da concordare",
    notePrezzo: "IVA esclusa",
  },

  // ─── ITER CONNESSIONE ────────────────────────────────────────────────────────
  // Include: iter completo connessione rete elettrica (E-Distribuzione, Terna, GSE),
  // schema unifilare in omaggio, registrazione Terna GAUDI',
  // apertura GSE e stipula contratto Ritiro Dedicato
  {
    id: "iter-1",
    categoria: "Iter Connessione",
    nome: "Iter Connessione fino a 6 kWp",
    descrizione: "Iter completo connessione impianto FV fino a 6 kWp (semplificato o ordinario). Include schema unifilare in omaggio, registrazione Terna GAUDI', apertura GSE, stipula contratto Ritiro Dedicato.",
    prezzoStandard: 350,
    prezzoForniture: 250,
    prezzoPremium: 200,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "iter-2",
    categoria: "Iter Connessione",
    nome: "Iter Connessione fino a 10 kWp",
    descrizione: "Iter completo connessione impianto FV fino a 10 kWp (semplificato o ordinario). Include schema unifilare in omaggio, registrazione Terna GAUDI', apertura GSE, stipula contratto Ritiro Dedicato.",
    prezzoStandard: 500,
    prezzoForniture: 400,
    prezzoPremium: 300,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "iter-3",
    categoria: "Iter Connessione",
    nome: "Iter Connessione fino a 20 kWp",
    descrizione: "Iter completo connessione impianto FV fino a 20 kWp (semplificato o ordinario). Include schema unifilare in omaggio, registrazione Terna GAUDI', apertura GSE, stipula contratto Ritiro Dedicato.",
    prezzoStandard: 700,
    prezzoForniture: 600,
    prezzoPremium: 500,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "iter-4",
    categoria: "Iter Connessione",
    nome: "Iter Connessione fino a 50 kWp",
    descrizione: "Iter completo connessione impianto FV fino a 50 kWp (semplificato o ordinario). Include schema unifilare in omaggio, registrazione Terna GAUDI', apertura GSE, stipula contratto Ritiro Dedicato.",
    prezzoStandard: 800,
    prezzoForniture: 700,
    prezzoPremium: 600,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "iter-5",
    categoria: "Iter Connessione",
    nome: "Iter Connessione fino a 100 kWp",
    descrizione: "Iter completo connessione impianto FV fino a 100 kWp (semplificato o ordinario). Include schema unifilare in omaggio, registrazione Terna GAUDI', apertura GSE, stipula contratto Ritiro Dedicato.",
    prezzoStandard: 1500,
    prezzoForniture: 1000,
    prezzoPremium: 700,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "iter-6",
    categoria: "Iter Connessione",
    nome: "Iter Connessione fino a 200 kWp",
    descrizione: "Iter completo connessione impianto FV fino a 200 kWp (semplificato o ordinario). Include schema unifilare in omaggio, registrazione Terna GAUDI', apertura GSE, stipula contratto Ritiro Dedicato.",
    prezzoStandard: 2500,
    prezzoForniture: 2000,
    prezzoPremium: 1700,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "iter-7",
    categoria: "Iter Connessione",
    nome: "Iter Connessione fino a 500 kWp",
    descrizione: "Iter completo connessione impianto FV fino a 500 kWp (semplificato o ordinario). Include schema unifilare in omaggio, registrazione Terna GAUDI', apertura GSE, stipula contratto Ritiro Dedicato.",
    prezzoStandard: 3500,
    prezzoForniture: 3000,
    prezzoPremium: 2700,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "iter-8",
    categoria: "Iter Connessione",
    nome: "Iter Connessione fino a 1.000 kWp",
    descrizione: "Iter completo connessione impianto FV fino a 1.000 kWp (semplificato o ordinario). Include schema unifilare in omaggio, registrazione Terna GAUDI', apertura GSE, stipula contratto Ritiro Dedicato.",
    prezzoStandard: 4500,
    prezzoForniture: 4000,
    prezzoPremium: 3500,
    notePrezzo: "IVA esclusa",
  },
  {
    id: "iter-9",
    categoria: "Iter Connessione",
    nome: "Iter Connessione fino a 1.500 kWp",
    descrizione: "Iter completo connessione impianto FV fino a 1.500 kWp (semplificato o ordinario). Include schema unifilare in omaggio, registrazione Terna GAUDI', apertura GSE, stipula contratto Ritiro Dedicato.",
    prezzoStandard: 5500,
    prezzoForniture: 5000,
    prezzoPremium: 4500,
    notePrezzo: "IVA esclusa",
  },

  // ─── GSE ─────────────────────────────────────────────────────────────────────
  {
    id: "gse-1",
    categoria: "GSE",
    nome: "Cambio Titolarità Contratti GSE (SSP/RID)",
    descrizione: "Trasferimento titolarità tariffa incentivante e/o convenzione cessione energia SSP/RID. Include aggiornamento dichiarazione antimafia sul portale GSE.",
    prezzoStandard: 200,
    prezzoForniture: 150,
    prezzoPremium: 100,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "gse-2",
    categoria: "GSE",
    nome: "Antimafia (documentazione GSE)",
    descrizione: "Compilazione, aggiornamento e caricamento telematico documentazione antimafia sul portale GSE. Necessario per incentivi GSE superiori a €150.000.",
    prezzoStandard: 250,
    prezzoForniture: 150,
    prezzoPremium: 100,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "gse-3",
    categoria: "GSE",
    nome: "Emissione Fatture sul Portale GSE",
    descrizione: "Emissione per conto del cliente delle fatture di vendita energia elettrica ceduta in rete al GSE.",
    prezzoStandard: 90,
    prezzoForniture: 50,
    prezzoPremium: 30,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "gse-4",
    categoria: "GSE",
    nome: "Fuel Mix",
    descrizione: "Compilazione e inserimento telematico del fuel mix disclosure sul portale GSE. Obbligatorio per tutti i titolari di convenzione RID.",
    prezzoStandard: 90,
    prezzoForniture: 50,
    prezzoPremium: 30,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "gse-5",
    categoria: "GSE",
    nome: "Verifica e Recupero Incentivi GSE",
    descrizione: "Verifica corretta erogazione incentivi GSE dall'attivazione della tariffa incentivante. Allineamento dati produzione mensile/annuale e riconteggio importi spettanti.",
    prezzoStandard: "10% importi recuperati",
    prezzoForniture: "9% importi recuperati",
    prezzoPremium: "8% importi recuperati",
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },

  // ─── AGENZIA DELLE DOGANE ─────────────────────────────────────────────────────
  {
    id: "dogane-1",
    categoria: "Agenzia delle Dogane",
    nome: "Denuncia Officina Elettrica — Cessione Parziale o Totale",
    descrizione: "Denuncia impianto produzione energia elettrica (potenza > 20 kWp) presso Ufficio Doganale. Ottenimento Licenza fiscale d'esercizio (autoconsumo) o Autorizzazione doganale (cessione totale).",
    prezzoStandard: 600,
    prezzoForniture: 550,
    prezzoPremium: 500,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "dogane-2",
    categoria: "Agenzia delle Dogane",
    nome: "Denuncia Officina Elettrica — Regime SEU",
    descrizione: "Denuncia impianto produzione energia elettrica (potenza > 20 kWp) in regime S.E.U. (Sistema Efficiente di Utenza) presso Ufficio Doganale.",
    prezzoStandard: 600,
    prezzoForniture: 550,
    prezzoPremium: 500,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "dogane-3",
    categoria: "Agenzia delle Dogane",
    nome: "Dichiarazione di Consumo — Cessione Parziale (annuale)",
    descrizione: "Elaborazione, presentazione e invio telematico dichiarazione consumo annuale officina elettrica in regime cessione parziale. Scadenza 31 marzo.",
    prezzoStandard: 700,
    prezzoForniture: 600,
    prezzoPremium: 500,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "dogane-4",
    categoria: "Agenzia delle Dogane",
    nome: "Dichiarazione di Consumo — Cessione Totale (annuale)",
    descrizione: "Elaborazione, presentazione e invio telematico dichiarazione consumo annuale officina elettrica in regime cessione totale. Scadenza 31 marzo.",
    prezzoStandard: 700,
    prezzoForniture: 600,
    prezzoPremium: 500,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "dogane-5",
    categoria: "Agenzia delle Dogane",
    nome: "Dichiarazione di Consumo — Regime Commerciale SEU (annuale)",
    descrizione: "Elaborazione e invio telematico dichiarazione consumo annuale officina elettrica in regime S.E.U. Scadenza 31 marzo.",
    prezzoStandard: 700,
    prezzoForniture: 600,
    prezzoPremium: 500,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "dogane-6",
    categoria: "Agenzia delle Dogane",
    nome: "Cambio Intestazione Officina Elettrica — Regime SEU",
    descrizione: "Predisposizione documentazione per cambio intestazione titolarità licenza SEU dell'officina elettrica presso Agenzia delle Dogane.",
    prezzoStandard: 600,
    prezzoForniture: 550,
    prezzoPremium: 500,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },

  // ─── CONTO TERMICO 3.0 ────────────────────────────────────────────────────────
  {
    id: "ct-1",
    categoria: "Conto Termico 3.0",
    nome: "Conto Termico 3.0 — Incentivo 0-1.499 €",
    descrizione: "Gestione pratica Conto Termico 3.0 per valore incentivo da 0 a 1.499 €.",
    prezzoStandard: 280,
    prezzoForniture: 280,
    prezzoPremium: 280,
    notePrezzo: "IVA inclusa per privati, esclusa per aziende",
  },
  {
    id: "ct-2",
    categoria: "Conto Termico 3.0",
    nome: "Conto Termico 3.0 — Incentivo 1.500-2.999 €",
    descrizione: "Gestione pratica Conto Termico 3.0 per valore incentivo da 1.500 a 2.999 €.",
    prezzoStandard: 350,
    prezzoForniture: 350,
    prezzoPremium: 350,
    notePrezzo: "IVA inclusa per privati, esclusa per aziende",
  },
  {
    id: "ct-3",
    categoria: "Conto Termico 3.0",
    nome: "Conto Termico 3.0 — Incentivo 3.000-5.999 €",
    descrizione: "Gestione pratica Conto Termico 3.0 per valore incentivo da 3.000 a 5.999 €.",
    prezzoStandard: 450,
    prezzoForniture: 450,
    prezzoPremium: 450,
    notePrezzo: "IVA inclusa per privati, esclusa per aziende",
  },
  {
    id: "ct-4",
    categoria: "Conto Termico 3.0",
    nome: "Conto Termico 3.0 — Incentivo 6.000-10.000 €",
    descrizione: "Gestione pratica Conto Termico 3.0 per valore incentivo da 6.000 a 10.000 €.",
    prezzoStandard: "€350 + 3% erogato (esito positivo)",
    prezzoForniture: "€350 + 3% erogato (esito positivo)",
    prezzoPremium: "€350 + 3% erogato (esito positivo)",
    notePrezzo: "IVA inclusa per privati, esclusa per aziende",
  },
  {
    id: "ct-5",
    categoria: "Conto Termico 3.0",
    nome: "Conto Termico 3.0 — Incentivo 10.001-15.000 €",
    descrizione: "Gestione pratica Conto Termico 3.0 per valore incentivo da 10.001 a 15.000 €.",
    prezzoStandard: "€500 + 3% erogato (esito positivo)",
    prezzoForniture: "€500 + 3% erogato (esito positivo)",
    prezzoPremium: "€500 + 3% erogato (esito positivo)",
    notePrezzo: "IVA inclusa per privati, esclusa per aziende",
  },
  {
    id: "ct-6",
    categoria: "Conto Termico 3.0",
    nome: "Conto Termico 3.0 — Incentivo 15.001-20.000 €",
    descrizione: "Gestione pratica Conto Termico 3.0 per valore incentivo da 15.001 a 20.000 €.",
    prezzoStandard: "€1.100 + 3% erogato (esito positivo)",
    prezzoForniture: "€1.100 + 3% erogato (esito positivo)",
    prezzoPremium: "€1.100 + 3% erogato (esito positivo)",
    notePrezzo: "IVA inclusa per privati, esclusa per aziende",
  },
  {
    id: "ct-7",
    categoria: "Conto Termico 3.0",
    nome: "Conto Termico 3.0 — Incentivo oltre 20.000 €",
    descrizione: "Gestione pratica Conto Termico 3.0 per valore incentivo superiore a 20.000 €.",
    prezzoStandard: "Chiedere valutazione",
    prezzoForniture: "Chiedere valutazione",
    prezzoPremium: "Chiedere valutazione",
    notePrezzo: "IVA inclusa per privati, esclusa per aziende",
  },

  // ─── ARERA ───────────────────────────────────────────────────────────────────
  {
    id: "arera-1",
    categoria: "ARERA",
    nome: "Compliance Completa N.03 Obblighi Annuali ARERA",
    descrizione: "Espletamento 3 adempimenti annuali ARERA: I. Dati Tecnici Produttori, II. Dichiarazione Preliminare Unbundling, III. Contributo Funzionamento Autorità.",
    prezzoStandard: 350,
    prezzoForniture: 250,
    prezzoPremium: 200,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "arera-2",
    categoria: "ARERA",
    nome: "ARERA — Dati Tecnici Produttori",
    descrizione: "Espletamento adempimento annuale ARERA Dati Tecnici Produttori sul portale (scadenza marzo-aprile). Obbligatorio per operatori che producono energia elettrica senza diritto all'esonero.",
    prezzoStandard: 350,
    prezzoForniture: 250,
    prezzoPremium: 200,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "arera-3",
    categoria: "ARERA",
    nome: "ARERA — Dichiarazione Preliminare Unbundling",
    descrizione: "Espletamento obbligo annuale ARERA Dichiarazione Preliminare Unbundling (scadenza 90 gg dall'approvazione del bilancio societario).",
    prezzoStandard: 90,
    prezzoForniture: 50,
    prezzoPremium: 30,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "arera-4",
    categoria: "ARERA",
    nome: "ARERA — Contributo Funzionamento Autorità",
    descrizione: "Espletamento obbligo annuale ARERA Contributo per il Funzionamento dell'Autorità (scadenza indicativamente dicembre-febbraio).",
    prezzoStandard: 90,
    prezzoForniture: 50,
    prezzoPremium: 30,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "arera-5",
    categoria: "ARERA",
    nome: "Cambio Intestazione Anagrafica — Portale ARERA",
    descrizione: "Creazione anagrafica Società subentrante e cambio intestazione anagrafica esistente sul portale ARERA.",
    prezzoStandard: 90,
    prezzoForniture: 50,
    prezzoPremium: 30,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },

  // ─── TERNA ────────────────────────────────────────────────────────────────────
  {
    id: "terna-1",
    categoria: "Terna",
    nome: "Cambio Intestazione Anagrafica CENSIMP — Portale GAUDI' Terna",
    descrizione: "Migrazione anagrafica impianto dell'attuale società sul portale GAUDI' di Terna in capo alla nuova anagrafica impianti di proprietà (delibera AEEG ARG/elt 124/10).",
    prezzoStandard: 90,
    prezzoForniture: 50,
    prezzoPremium: 30,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "terna-2",
    categoria: "Terna",
    nome: "Rilevazione GSTAT Terna",
    descrizione: "Compilazione e invio rilevazione statistica produzione/consumo energia elettrica tramite portale GSTAT di Terna (entro il 15 di ogni mese). Obbligatorio per impianti non FV con potenza > 200 kWp in stato 'in esercizio' su GAUDI'.",
    prezzoStandard: 180,
    prezzoForniture: 120,
    prezzoPremium: 80,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },
  {
    id: "terna-3",
    categoria: "Terna",
    nome: "Fuel Mix",
    descrizione: "Compilazione e inserimento telematico fuel mix disclosure sul portale GSE. Obbligatorio per tutti i titolari di convenzione RID.",
    prezzoStandard: 90,
    prezzoForniture: 50,
    prezzoPremium: 30,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },

  // ─── DISTRIBUZIONE ────────────────────────────────────────────────────────────
  {
    id: "dist-1",
    categoria: "Distribuzione",
    nome: "Cambio Intestazione E-Distribuzione",
    descrizione: "Cambio titolarità del regolamento d'esercizio presso E-Distribuzione.",
    prezzoStandard: 300,
    prezzoForniture: 200,
    prezzoPremium: 150,
    notePrezzo: "Prezzi esenti IVA (Reverse charge Art. 17, c. 6 lett. a), DPR 633/72)",
  },

  // ─── BANDI ────────────────────────────────────────────────────────────────────
  {
    id: "bandi-1",
    categoria: "Bandi",
    nome: "Bando Agrisolare / PN RIC FTV SUD MASE — fino a 50 kWp",
    descrizione: "Gestione completa pratica bando Agrisolare e PN RIC FTV SUD MASE per impianti fino a 50 kWp.",
    prezzoStandard: "€300 + 5% erogato (esito positivo)",
    prezzoForniture: "€300 + 5% erogato (esito positivo)",
    prezzoPremium: "€300 + 5% erogato (esito positivo)",
    notePrezzo: "IVA esclusa",
  },
  {
    id: "bandi-2",
    categoria: "Bandi",
    nome: "Bando Agrisolare / PN RIC FTV SUD MASE — fino a 200 kWp",
    descrizione: "Gestione completa pratica bando Agrisolare e PN RIC FTV SUD MASE per impianti fino a 200 kWp.",
    prezzoStandard: "€500 + 4% erogato (esito positivo)",
    prezzoForniture: "€500 + 4% erogato (esito positivo)",
    prezzoPremium: "€500 + 4% erogato (esito positivo)",
    notePrezzo: "IVA esclusa",
  },
  {
    id: "bandi-3",
    categoria: "Bandi",
    nome: "Bando Agrisolare / PN RIC FTV SUD MASE — fino a 1.000 kWp",
    descrizione: "Gestione completa pratica bando Agrisolare e PN RIC FTV SUD MASE per impianti fino a 1.000 kWp.",
    prezzoStandard: "€1.000 + 3% erogato (esito positivo)",
    prezzoForniture: "€1.000 + 3% erogato (esito positivo)",
    prezzoPremium: "€1.000 + 3% erogato (esito positivo)",
    notePrezzo: "IVA esclusa",
  },
  {
    id: "bandi-4",
    categoria: "Bandi",
    nome: "Altri Bandi — Richiedere Prezzo",
    descrizione: "Gestione di altri bandi per contributi e incentivi. Contattare per valutazione.",
    prezzoStandard: "Richiedere prezzo",
    prezzoForniture: "Richiedere prezzo",
    prezzoPremium: "Richiedere prezzo",
    notePrezzo: "IVA esclusa",
  },
];

export const CATEGORIE = Array.from(new Set(LISTINO.map((s) => s.categoria)));

// Ordine fisso delle categorie per la sidebar
export const CATEGORIE_ORDINATE = [
  "Progettazione",
  "Iter Connessione",
  "GSE",
  "Agenzia delle Dogane",
  "Conto Termico 3.0",
  "ARERA",
  "Terna",
  "Distribuzione",
  "Bandi",
];

// Icone per categoria
export const ICONE_CATEGORIE: Record<string, string> = {
  "Progettazione": "📐",
  "Iter Connessione": "⚡",
  "GSE": "🌱",
  "Agenzia delle Dogane": "🏛️",
  "Conto Termico 3.0": "♻️",
  "ARERA": "📋",
  "Terna": "🔌",
  "Distribuzione": "🏗️",
  "Bandi": "🏆",
};

// Costanti pack (sincronizzate con server/db.ts)
export const PRATICHE_PER_PACK: Record<string, number> = {
  pack1: 21,
  pack2: 39,
  pack3: 80,
};
export const PRATICHE_RES_PER_PACK: Record<string, number> = {
  pack1: 16,
  pack2: 30,
  pack3: 60,
};
export const PRATICHE_BUS_PER_PACK: Record<string, number> = {
  pack1: 5,
  pack2: 9,
  pack3: 20,
};
